-record(frame_info, {name, 
                     class,
                     x,
                     y,
                     width,
                     height,
                     grid,
                     bg,
                     font,
                     fontsize,
                     paraIndent,
                     maxlines,
                     continue,
                     break}).
